version: "3.7"


services:
    nginx:
        image: nginx:latest
        volumes:
            - ./configuration/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./application/${PROJECT_NAME}:/var/www/html:ro
        ports:
            - "80:80"
            - "8080:8080" # adminer
        depends_on:
            - php
            - postgresql
        networks:
            - nginx

    php:
        build:
            context: ./dockerfiles/php
            args:
                - USER_ID
                - GROUP_ID
        volumes:
            - ./application/${PROJECT_NAME}:/var/www/html
            - ./configuration/php/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
        networks:
            - nginx
            - postgresql

    postgresql:
        image: postgres:latest
        volumes:
            - postgresql:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        networks:
            - postgresql
            - adminer

    adminer:
        image: adminer:latest
        networks:
            - adminer
            - nginx


networks:
    nginx:
    postgresql:
    adminer:


volumes:
    postgresql:
