version: "3.7"


services:
    nginx:
        image: nginx:${NGINX_IMAGE_TAG}
        volumes:
            - ./configuration/nginx:/etc/nginx/conf.d:ro
            - ./application/${PROJECT_NAME}:/var/www/html:ro
        ports:
            - "80:80"
            - "8080:8080" # adminer
        restart: always
        depends_on:
            - php
            - postgresql
        networks:
            - nginx

    php:
        build:
            context: ./dockerfiles/php
            args:
                - PHP_FPM_IMAGE_TAG
                - USER_ID
                - GROUP_ID
        volumes:
            - ./application/${PROJECT_NAME}:/var/www/html
        restart: always
        networks:
            - nginx
            - postgresql

    postgresql:
        image: postgres:${POSTGRES_IMAGE_TAG}
        volumes:
            - postgresql:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        restart: always
        networks:
            - postgresql
            - adminer

    adminer:
        image: adminer:${ADMINER_IMAGE_TAG}
        depends_on:
            - postgresql
        restart: always
        networks:
            - adminer
            - nginx


networks:
    nginx:
    postgresql:
    adminer:


volumes:
    postgresql:
