version: "3.7"


services:
  nginx:
    image: nginx:${NGINX_IMAGE_TAG}
    volumes:
      - ./configuration/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./configuration/nginx/ssl:/etc/nginx/ssl:ro
      - ./application/${PROJECT_NAME}:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php
      - postgresql
    networks:
      nginx:
      selenium:
        aliases:
          - ${PROJECT_DOMAIN}

  php:
    build:
      context: ./dockerfiles/php
      args:
        - PHP_FPM_IMAGE_TAG
        - USER_ID
        - GROUP_ID
    volumes:
      - ./dockerfiles/php/entrypoint.sh:/home/www-data/custom-entrypoint.sh:ro
      - ./configuration/php/custom-php.ini:${PHP_INI_DIR}/conf.d/custom-php.ini:ro
      - ./application/${PROJECT_NAME}:/var/www/html
    restart: always
    networks:
      - nginx
      - postgresql
      - redis
      - selenium

  postgresql:
    image: postgres:${POSTGRES_IMAGE_TAG}
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: always
    networks:
      - postgresql
      - pgadmin

  redis:
    image: redis:${REDIS_IMAGE_TAG}
    volumes:
      - redis:/data
    restart: always
    networks:
      - redis

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_IMAGE_TAG}
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - postgresql
    restart: always
    networks:
      - pgadmin
      - nginx

  selenium:
    image: selenium/hub:${SELENIUM_IMAGE_TAG}
    depends_on:
      - php
    ports:
      - "${SELENIUM_PORT}:4444"
    networks:
      - selenium

  firefox:
    image: selenium/node-firefox:${FIREFOX_IMAGE_TAG}
    depends_on:
      - selenium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium
    networks:
      - selenium


networks:
  nginx:
  postgresql:
  redis:
  pgadmin:
  selenium:


volumes:
  postgresql:
  pgadmin:
  redis:
